deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - mkdir -p $HOME/tmp
    - cd $HOME/tmp
    - git clone https://github.com/DiegoRX/NFT-Project
    - cd NFT-Project
    - npm install
    - npm run build
    - rm -rf $DEPLOYPATH/*
    - cp -r $HOME/tmp/NFT-Project/out/* $DEPLOYPATH/
    - rm -rf $HOME/tmp/NFT-Project